AWSTemplateFormatVersion: '2019-09-09' 
Transform: AWS::Serverless-2016-10-31 
Description: API de envios

Resources:
  Envio:
    Type: AWS::Serverless::Function 
    Properties:
      Handler: index.handler
      Runtime: nodejs14.x
      Timeout: 100
      Events:
        ListProductos:
          Type: Api 
          Properties:
            Path: /envios/pendientes
            Method: get
        CreateEnvio:
          Type: Api 
          Properties:
            Path: /envios
            Method: post
        Producto:
          Type: Api 
          Properties:
            Path: /envios/{idEnvio}/entregado
            Method: put    